### ISSUE TITLE
Roadmap to follow - II (Himanshu)

### ISSUE THREAD

**Issue by Zolo-Ryan** [Himasnhu-AT/isro_proj#10]
- [ ] If new person is added then what happes with the 3 tables? `Contacts`, `RawContacts` and `Data` table
- [ ] What happens on deleting the user
- [ ] What happens on updating the user
- [ ] What happens to a field when the data inside of it exceeds its maximum size? Also what are the default sizes of each `field` in each `db`?
- [ ] Create a report for all of the above in `Sprints/Sprint34/himanshu/`

The above tasks need to be achieved by directly adding/deleting/modifying user into the `rooted android's db` by @Himasnhu-AT
