### ISSUE TITLE
Roadmap to follow

### ISSUE THREAD

**Issue by Zolo-Ryan** [Himasnhu-AT/isro_proj#5]
- [x] Create a simple android application to read contacts from the android device using `ContactsProvider`
  - [x] Take out the fields printed from that.
  - [x] Compare the fields with the vcf file.
  - [x] Figure out the total count of fields.
  - [x] Check and figure out what fields are missing and why.

- [ ] Find alternate export methods to expose more number of fields in vcf
