### ISSUE TITLE
Roadmap to follow (Arihant)

### ISSUE THREAD

**Issue by Zolo-Ryan** [Himasnhu-AT/isro_proj#6]
- [ ] Create a simple android application to read contacts from the the android device using `ContentProvider`
  - [ ] Take out the fields printed from that.
  - [ ] Compare the fields with the vcf file.
  - [ ] Figure out the total count of fields.
  - [ ] Check and figure out what fields are missing and why.

**Comment by Zolo-Ryan** [comment]
`ContentProvider` is an abstract class using which we can't make any objects
