### ISSUE TITLE
Roadmap to follow (Himanshu)

### ISSUE THREAD

**Issue by Zolo-Ryan** [Himasnhu-AT/isro_proj#7]
- [X] #8
  - [x] Extract out all the interesting dbs (`contacts`, `messages` or somone with similar name)
  - [x] Access all the fields of each db.
  - [x] Share with @Zolo-Ryan and @arihantjain-17 to help understand what fields are misssing in issue #6 and #5
