### ISSUE TITLE
Roadmap to follow - II

### ISSUE THREAD

**Issue by Zolo-Ryan** [Himasnhu-AT/isro_proj#9]
- [ ] If new person is added then what happes with the 3 tables? `Contacts`, `RawContacts` and `Data` table
- [ ] What happens on deleting the user
- [ ] What happens on updating the user
- [ ] What happens to a field when the data inside of it exceeds its maximum size? Also what are the default sizes of each `field`  in each `db`?
- [ ] Create a report for all of the above in `Sprints/Sprint34/zolo/`

The above tasks are to be completed using `ContactProvider`'s api by @Zolo-Ryan
